name: tasky
description: "A Todo App."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.1
  intl_phone_field: ^3.2.0
  iconly: ^1.0.1
  dotted_border: ^2.1.0
  equatable: ^2.0.5
  dartz: ^0.10.1
  internet_connection_checker: ^2.0.0
  http: ^1.2.2
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  flutter_secure_storage: ^9.2.2
  intl: ^0.19.0
  image_picker: ^1.1.2
  get_it: ^7.7.0
  flutter_services_binding: ^0.1.0
  http_parser: ^4.0.2
  bloc_concurrency: ^0.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/images/
    - assets/icons/

  fonts:
    - family: DMSans
      fonts:
        - asset: assets/fonts/DMSans-Regular.ttf
        - asset: assets/fonts/DMSans-Bold.ttf
          weight: 700

flutter_native_splash:
  android: true
  ios: false
  web: false

  background_image: "assets/images/splash.png"
  color: "#5F33E1"
  image: assets/logo.png
  # branding: "assets/images/logo.png"

  android_12:
    color: "#5F33E1"
    image: assets/logo.png
    branding: assets/logo.png
